### ISSUE TITLE
Passport-JWT Needs to target users based on payload

### ISSUE THREAD

**Issue by CentroDL** [rapala61/express_auth_student_template#3]
This is a line in the passport jwt strategy that gets the user from the payload:

``` rb
    User.findOne({id: jwt_payload.sub}, function(err, user) {
```

It turns out that the id: THING.sub parameter doesnt sit well with mongoose. So we were getting the wrong user after logging in. I'd suggest targeting the query via a unique variable inside the payload:

``` rb
User.findOne({username: jwt_payload._doc.username}, function(err, user) {
```

**Comment by rapala61** [comment]
Fix merged to master
